# Generated by Django 5.1.4 on 2024-12-11 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MättöMittari', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('ruoka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MättöMittari.ruoka')),
            ],
            options={
                'verbose_name_plural': 'arviot',
            },
        ),
    ]
