# Generated by Django 5.1.4 on 2024-12-11 17:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MättöMittari', '0002_arvio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruoka',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
