# Generated by Django 5.1.4 on 2024-12-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MättöMittari', '0004_arvio_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruoka',
            name='ainekset',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
